name: CI - Build STM32 Single-Core Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # === Build firmware (Debug) ===
      - name: Build firmware (Debug)
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: '.'
          project-target: 'Debug'

      # === Upload ELF artifacts ===
      - name: Upload ELF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-wireless-mqtt-node-elf
          path: |
            *.elf
            *.bin
            *.hex
