name: CI - Build STM32 Single-Core Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build STM32CubeIDE project
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: '.'
          project-target: 'stm32_wireless_mqtt_node/Debug'

      - name: List files after build
        run: |
          echo "=== Workspace ==="
          ls -R

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-wireless-mqtt-node
          path: |
            **/*.elf
            **/*.bin
            **/*.hex
