name: CI - Build STM32 Single-Core Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # === Build firmware ===
      - name: Build firmware (Debug)
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: 'stm32_wireless_mqtt_node'
          project-target: 'stm32_wireless_mqtt_node/Debug'

      # === Upload build artifacts ===
      - name: Upload ELF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-wireless-mqtt-node-elf
          path: |
            stm32_wireless_mqtt_node/Debug/*.elf
            stm32_wireless_mqtt_node/Debug/*.bin
            stm32_wireless_mqtt_node/Debug/*.hex
