name: CI/CD - Build and Release STM32 Single-Core Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # release oluşturmak için gerekli

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # tag ve commit geçmişi için tam clone

      - name: Build STM32CubeIDE project
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: '.'
          project-target: 'stm32_wireless_mqtt_node/Debug'

      - name: List files after build
        run: |
          echo "=== Workspace ==="
          ls -R || true

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG =~ (v[0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION=${BASH_REMATCH[1]}
            CLEAN_VERSION=$(echo "$VERSION" | sed 's/v//; s/\.//g')
            echo "TAG_NAME=$VERSION" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=stm32wireless$CLEAN_VERSION" >> $GITHUB_OUTPUT
          else
            DATE=$(date +'%Y%m%d')
            SHA=$(git rev-parse --short HEAD)
            echo "TAG_NAME=auto-$DATE-$SHA" >> $GITHUB_OUTPUT
            echo "RELEASE_NAME=stm32wireless-$DATE-$SHA" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_version.outputs.TAG_NAME }}
          name: ${{ steps.extract_version.outputs.RELEASE_NAME }}
          files: |
            **/*.bin
            **/*.elf
            **/*.hex
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stm32-wireless-mqtt-node
          path: |
            **/*.elf
            **/*.bin
            **/*.hex
